// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZLC2A_8ieovrB687pjh6wrc_TcGEdxE',
    appId: '1:940200751102:web:08d0a51b52886b596f5aaf',
    messagingSenderId: '940200751102',
    projectId: 'zebrot-2577d',
    authDomain: 'zebrot-2577d.firebaseapp.com',
    storageBucket: 'zebrot-2577d.appspot.com',
    measurementId: 'G-C6BZTEQ3Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2kUGgHm_vHGfGM_FepwkxJUkxgHTEkhQ',
    appId: '1:940200751102:android:8619b13dfe4201696f5aaf',
    messagingSenderId: '940200751102',
    projectId: 'zebrot-2577d',
    storageBucket: 'zebrot-2577d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1OCPNd2Ir4FSmbH57OHxW3redeyGNJuU',
    appId: '1:940200751102:ios:5f708ec9024dd64e6f5aaf',
    messagingSenderId: '940200751102',
    projectId: 'zebrot-2577d',
    storageBucket: 'zebrot-2577d.appspot.com',
    iosBundleId: 'com.example.neeicum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1OCPNd2Ir4FSmbH57OHxW3redeyGNJuU',
    appId: '1:940200751102:ios:5f708ec9024dd64e6f5aaf',
    messagingSenderId: '940200751102',
    projectId: 'zebrot-2577d',
    storageBucket: 'zebrot-2577d.appspot.com',
    iosBundleId: 'com.example.neeicum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvZLC2A_8ieovrB687pjh6wrc_TcGEdxE',
    appId: '1:940200751102:web:33e2641315d21a126f5aaf',
    messagingSenderId: '940200751102',
    projectId: 'zebrot-2577d',
    authDomain: 'zebrot-2577d.firebaseapp.com',
    storageBucket: 'zebrot-2577d.appspot.com',
    measurementId: 'G-8S3LSCBGCG',
  );
}
